### ISSUE TITLE
What does this pyqt5 encrypted data do?

### ISSUE THREAD

**Issue by hoemotion** [hritsh/discord-autosend#1]
Im not sur if i can trust this code, why did you encrypt it, does it grab my
token/email/password/ip-address?

**Comment by hritsh** [comment]
No 😂, it doesn't send any information, just stores your login info in a .dat file on your own hard disk when you click save details, so that you wouldn't need to enter it again. Theres zero uploading of any information in the whole code, everything is processed on your machine.

**Comment by hoemotion** [comment]
> No 😂, it doesn't send any information, just stores your login info in a .dat file on your own hard disk when you click save details, so that you wouldn't need to enter it again. Theres zero uploading of any information in the whole code, everything is processed on your machine.

Okay thx, but was it really necessary to encrypt that, is it possible for me to decrypt that?

**Comment by hritsh** [comment]
> > No 😂, it doesn't send any information, just stores your login info in a .dat file on your own hard disk when you click save details, so that you wouldn't need to enter it again. Theres zero uploading of any information in the whole code, everything is processed on your machine.
> 
> Okay thx, but was it really necessary to encrypt that, is it possible for me to decrypt that?

It isn't really "encrypted", just stored as a .dat file so the details cant be viewed with a regular text editor like notepad. They can be read with a .dat viewer or an advanced text editor / IDE like VS Code and also by Python but if you want, you can store them in a regular text file, no problem with that too.

**Comment by hoemotion** [comment]
> It isn't really "encrypted", just stored as a .dat file so the details cant be viewed with a regular text editor like notepad. They can be read with a .dat viewer or an advanced text editor / IDE like VS Code and also by Python but if you want, you can store them in a regular text file, no problem with that too.

So pyqt5 is automatically decrypted, when i use vsc?
I mean the x01\x96\x84\x78\x9 stuff

**Comment by hritsh** [comment]
> > It isn't really "encrypted", just stored as a .dat file so the details cant be viewed with a regular text editor like notepad. They can be read with a .dat viewer or an advanced text editor / IDE like VS Code and also by Python but if you want, you can store them in a regular text file, no problem with that too.
> 
> So pyqt5 is automatically decrypted, when i use vsc? I mean the x01\x96\x84\x78\x9 stuff

Oh, pyqt5 is just the tool that shows the GUI, the "encryption" is only for your login details, which are stored in the .dat file. You could probably install a VS Code extensions to view .dat files, though im not completely sure. But it can be read using python's inbuilt pickle module. You can read more about it [here](https://www.geeksforgeeks.org/understanding-python-pickling-example/).
