### ISSUE TITLE
Error saying that I need 32-bit or 64-bit

### ISSUE THREAD

**Issue by Joyen12** [hritsh/discord-autosend#2]
Hello,
I get this error :

<img width="289" alt="Capture d’écran 2021-12-24 à 2 20 54 PM" src="https://user-images.githubusercontent.com/27678813/147324220-d9534164-c840-4d55-9872-0cc65f4af43f.png">

I guess maybe my windows version is too old...? (it's windows 7)

Is there a way to build from source or another way to have it on my windows

Thanks a lot

**Comment by Joyen12** [comment]
?

**Comment by hritsh** [comment]
I can't really confirm as I dont have a 32 bit system :/ so I'm not sure if pyqt5 or the libraries used are 32 bit compatible, but you can try building it from source by first installing the libraries required and then using pyinstaller to build the exe on your computer.
